FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY ElixirProject_Willard.csproj .
RUN dotnet restore ElixirProject_Willard.csproj

COPY . .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./

ENTRYPOINT [ "./ElixirProject_Willard" ]